---
title: "DataSim"
author: "Lisa DeBruine"
date: "19/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(faux)
library(lmerTest)
```

## Load and process data

```{r}
data <- read_csv("data/simplified_data.csv") %>%
  mutate(size = size_delta/10,
         color = factor(color),
         contrast = factor(contrast)) %>%
  add_contrast("color", colnames = "color.e") %>%
  add_contrast("contrast", colnames = "contrast.e")
```

* 7 subjects
* color = T/F (within subject)
* contrast = +/- (between subject)
* size_delta = seq(-80,+80, 10) w/in subject
* response = 0/1


```{r}
ggplot(data, aes(x = size_delta, y = response,
                 color = color)) +
  facet_grid(~subjectID) +
  stat_summary()
```


## Model to get parameter estimate

```{r}
model <- glmer(response ~ color.e * contrast.e * size +
                 (1 | subjectID), 
               data = data, 
               family = binomial(link = "logit"))

summary(model)
```


```{r}
pred_data <- predict(model, type = "response")
```

```{r}
ggplot(data, aes(x = size_delta, y = pred_data,
                 color = color)) +
  facet_grid(~subjectID) +
  stat_summary()
```




```{r}
est <- broom.mixed::tidy(model)
```


## Data Exclusions by contrast


```{r}
included <- count(data, subjectID, color, contrast, size_delta) %>% 
  mutate(n = ifelse(size_delta == 0, n/2, n)) %>%
  group_by(subjectID, contrast) %>%
  summarise(mean = mean(n), .groups = "drop") %>%
  summarise(mean = mean(mean), .groups = "drop") %>%
  pull(mean)
```


## Fake some data

```{r}
# logit functions

logit <- function(x) { log(x / (1 - x)) }
inv_logit <- function(x) { 1 / (1 + exp(-x)) }
```

```{r}
# simulation function

simdata <- function(fixef,
                    subj_n = 100, 
                    trial_n = 24,
                    excluded = 0) {
  add_random(subjectID = subj_n) %>%
    add_random(trial = trial_n) %>%
    add_within(contrast = c("positive", "negative")) %>%
    add_within(color = c(TRUE, FALSE)) %>%
    add_within(size_delta = seq(0, 80, 10)) %>%
    add_within(sign_delta = c("+", "-")) %>%
    add_ranef("subjectID", sub_i = fixef$`sd__(Intercept)`) %>%
    mutate(size_delta = as.character(size_delta) %>% as.integer() *
             ifelse(sign_delta == "+", 1, -1),
           size = size_delta/10,
           color = factor(color),
           contrast = factor(contrast)) %>%
    add_contrast("color", colnames = "color.e") %>%
    add_contrast("contrast", colnames = "contrast.e") %>%
    mutate(
      # calculate gaussian DV
      Y = fixef$`(Intercept)` + sub_i + 
        fixef$color.e * color.e +
        fixef$contrast.e * contrast.e +
        fixef$size * size +
        fixef$`color.e:contrast.e` * color.e * contrast.e +
        fixef$`color.e:size` * color.e * size +
        fixef$`contrast.e:size` * contrast.e * size +
        fixef$`color.e:contrast.e:size` * color.e * contrast.e * size,
      pr = inv_logit(Y), # transform to probability of getting 1
      response = rbinom(nrow(.), 1, pr) # sample from bernoulli distribution
    ) %>%
    select(subjectID, 
           contrast, color, size_delta, 
           color.e, contrast.e, size, 
           response) %>%
    messy(prop = excluded, response)
}
```

```{r}
# set parameters
subj_n <- 100
trial_n <- 24
excluded <- (trial_n - included)/trial_n

# fixed and random effects
fixef <- setNames(object = est$estimate, 
                  nm = est$term) %>%
  as.list()
```

```{r}
# simulate one dataset
simdata1 <- simdata(fixef = fixef, 
                    subj_n = subj_n, 
                    trial_n = trial_n,
                    excluded = excluded)
```


## Analysis PSE

```{r, message = FALSE}
analyse <- function(simdata1) {
  simplified_PSEs = simdata1 %>% 
    group_by(color, subjectID, contrast) %>% 
    nest() %>% 
    mutate(data = map(data, ~ glm(response ~ size_delta, family=binomial(link='logit'), data = .))) %>%
    # get the coefficients
    mutate(data = map(data, ~ coefficients(.))) %>% 
    # convert coefficients from weird format
    mutate(data = map(data, ~ as_tibble(as.list(.)))) %>% 
    # convert back to a normal table with 1 row per boot * condition * subject
    unnest(data) %>% 
    # make coefficients easier to manage
    rename(intercept = `(Intercept)`) %>% 
    mutate(pse = -intercept/size_delta)
  
  afex::aov_ez(
    id="subjectID", 
    dv="pse", 
    simplified_PSEs, 
    within=c("color", "contrast"), 
    anova_table = list(correction="none", es = "pes")) %>% 
    # use pes to calculate cohen's f
    `$`('anova_table') %>% 
    mutate(cohens_f = sqrt(pes/(1-pes))) %>% 
    # why are the row names so hard to access?
    as.data.frame() %>% 
    rownames_to_column("effect")
}
```

## Power analysis

```{r}
power_table <- map_df(1:10, ~{ simdata(fixef) %>% analyse() })
```

```{r}
ggplot(power_table, aes(x = cohens_f, color = effect)) +
  geom_density()
```






